# Define a dictionary of emojis with short, easy-to-recall names
emoji_dict = {
    "smiley": "😀",
    "big_eyes": "😃",
    "smile_eyes": "😄",
    "beaming": "😁",
    "squinting": "😆",
    "sweat": "😅",
    "tears_of_joy": "😂",
    "rolling_laugh": "🤣",
    "smiling": "😊",
    "halo": "😇",
    "slight_smile": "🙂",
    "upside_down": "🙃",
    "wink": "😉",
    "heart_eyes": "😍",
    "blowing_kiss": "😘",
    "kissing": "😗",
    "kissing_smile": "😙",
    "kissing_closed": "😚",
    "relaxed": "☺️",
    "neutral": "😐",
    "expressionless": "😑",
    "no_mouth": "😶",
    "smirk": "😏",
    "persevere": "😣",
    "relieved": "😥",
    "open_mouth": "😮",
    "hushed": "😯",
    "astonished": "😲",
    "flushed": "😳",
    "pleading": "🥺",
    "dizzy": "😵",
    "woozy": "🥴",
    "mask": "😷",
    "thermometer": "🤒",
    "bandage": "🤕",
    "nauseated": "🤢",
    "vomiting": "🤮",
    "sneeze": "🤧",
    "cowboy": "🤠",
    "horns": "😈",
    "angry_horns": "👿",
    "skull": "💀",
    "ghost": "👻",
    "cat_smile": "😺",
    "cat_big_smile": "😸",
    "cat_tears": "😹",
    "cat_heart": "😻",
    "cat_wry": "😼",
    "cat_kissing": "😽",
    "cat_weary": "🙀",
    "cat_crying": "😿",
    "cat_pouting": "😾"
}

# Function to get an emoji by its short name
def get_emoji(name):
    return emoji_dict.get(name, "Emoji not found")